### ISSUE TITLE
2.0怎么安装

### ISSUE THREAD

**Issue by M1k0er** [jeffzh3ng/Fuxi-Scanner#12]
如题

**Comment by jeffzh3ng** [comment]
更新了 README.md 增加了大致安装方式

**Comment by M1k0er** [comment]
没法启动，看了日志：
Traceback (most recent call last):
  File "./fuxi_manage.py", line 8, in <module>
    from fuxi.web.router import flask_app
  File "/home/root0er/Desktop/root0er/bugsecurity/bug/tool/vul/fuxi/fuxi/web/router.py", line 9, in <module>
    from fuxi.web.flask_app import flask_app
  File "/home/root0er/Desktop/root0er/bugsecurity/bug/tool/vul/fuxi/fuxi/web/flask_app.py", line 14, in <module>
    from fuxi.common.utils.logger import logger
  File "/home/root0er/Desktop/root0er/bugsecurity/bug/tool/vul/fuxi/fuxi/common/utils/logger.py", line 14, in <module>
    from instance.config import LOGGER_PATH
ImportError: cannot import name 'LOGGER_PATH'

**Comment by jeffzh3ng** [comment]
原配置文件有问题，已经修改了，重新拉一下代码，然后用新的 _config.py 改成 config.py 再重新配置一下

**Comment by M1k0er** [comment]
数据库配置貌似有问题，账号密码都设置在，还是提示2019-10-17 11:46:45 ERROR - db_init.py[40]: database initialization failure: there are no users authenticated

def databases_init():
    try:
        if not DBFuxiAdmin.find_one():
            DBFuxiAdmin.add_admin(
                username="fuxi_scanner", password="W94MRYDqOZ",
                nick="14b3xfY1wd", email="W94MRYDqOZ",
            )
        if not DBPocsuitePlugin.find_one():
            _poc_path = os.path.abspath(os.path.dirname(__file__)) + "/pocs"
            for poc_filename in os.listdir(_poc_path):
                with open(_poc_path + "/" + poc_filename, "r", encoding="UTF-8") as poc_read:
                    poc_str = poc_read.read()
                    poc_data = poc_parser(poc_str)
                    DBPocsuitePlugin.add(
                        name=poc_data['name'], poc_str=poc_str, filename=poc_filename,
                        app=poc_data['app'], poc_type=poc_data['type'], op="fuxi"

**Comment by XTeam-Wing** [comment]
代码没问题,能够正常运行,自己试一下,我的MongoDB设置的是空口令.

**Comment by jeffzh3ng** [comment]
原本的代码没有写 mongoDB 的认证功能 现在加上了 你需要重新拉下代码 修改使用新的 _config.py 改成 config.py 再重新配置，如果依旧提示认证失败，请检查一下你 mongoDB 数据库的用户权限配置。

**Comment by jeffzh3ng** [comment]
你贴的这段代码是用来添加默认 fuxi 系统用户的不是数据库的 数据库在 instance/config.py  里面配置
fuxi 的默认用户是fuxi 密码是whoami

**Comment by Maskhe** [comment]
师傅，前端框架用的是哪个程序

**Comment by jeffzh3ng** [comment]
vue 
Project: https://github.com/jeffzh3ng/fuxi-ui

**Comment by Maskhe** [comment]
> 
> 
> vue
> Project: https://github.com/jeffzh3ng/fuxi-ui

我还以为用的是开源的前端ui,这个是师傅自己写的吗？

**Comment by jeffzh3ng** [comment]
历史遗留 bug 已解决，该issus将关闭
