### ISSUE TITLE
左侧导航没有 portscanner?

### ISSUE THREAD

**Issue by kylinpoet** [jeffzh3ng/Fuxi-Scanner#13]
![TIM截图20191124084442](https://user-images.githubusercontent.com/6766883/69487544-d9ca0480-0e96-11ea-8042-6201b90b576c.jpg)
如题

**Comment by jeffzh3ng** [comment]
这个功能没写 这个项目要暂时停一会 最近忙别的事情 年底开始写

**Comment by jeffzh3ng** [comment]
端口扫描功能已上线，该issus将关闭
