### ISSUE TITLE
ubtuntu16.04无法通过docker启动fuxi

### ISSUE THREAD

**Issue by lyx744** [jeffzh3ng/Fuxi-Scanner#15]
首先，通过
![image](https://user-images.githubusercontent.com/28533907/74712679-d65dd380-5261-11ea-93e6-a996da7c77c9.png)
成功创建了docker容器，但此时无法访问127.0.0.1:5000；
进入容器内部查看进程，发现只有
![image](https://user-images.githubusercontent.com/28533907/74712757-0a38f900-5262-11ea-9611-fcf3701e5eb3.png)
此时尝试通过./fuxi_manage.sh命令启动，报错
![image](https://user-images.githubusercontent.com/28533907/74712806-2ccb1200-5262-11ea-998e-5e10a31ca735.png)

docker版本19.03.6

**Comment by jeffzh3ng** [comment]
docker里的日志都在 /data/ 下面的目录里，可以贴一份我看看。
另外在/opt/fuxi/目录下 直接执行 python3.7 fuxi_mange.py 查看有没有报错
然后在执行 celery worker -A fuxi_celery_worker.celery 看看报错是什么

**Comment by lyx744** [comment]
![image](https://user-images.githubusercontent.com/28533907/74834175-dfc86800-5355-11ea-86ce-97032557e841.png)
日志和直接执行fuxi_manage.py都是报的这个错，mongodb没启动成功
celery无报错

**Comment by jeffzh3ng** [comment]
嗯 这个问题第一次看到，是docker里的mongo数据库没有起来
看一下 /etc/mongodb.conf 里面dbpath配置是什么
执行 service mongodb restart 看看数据库能不能手动起来
我这边再复现看看

**Comment by lyx744** [comment]
查看mongodb的log，发现是/data/mongodb的权限不够，增加权限后可以成功启动了
exception in initAndListen: IllegalOperation: Attempted to create a lock file on a read-only directory: /data/mongodb, terminating

**Comment by jeffzh3ng** [comment]
手动启动服务的嘛，重启下该容器看看还能不能工作，执行docker restart fuxi_docker 
我这边在ubuntu 18.04 下没有复现出来
我在启动文件里加了一条赋权命令，希望可以解决这个问题
chmod -R +w /data/mongodb

**Comment by lyx744** [comment]
重启容器也可以正常启动，感谢师傅，辛苦了^ ^

**Comment by jeffzh3ng** [comment]
历史遗留 bug 已解决，该issus将关闭
