### ISSUE TITLE
what: 192.168.56.2:3443

### ISSUE THREAD

**Issue by hktalent** [jeffzh3ng/Fuxi-Scanner#7]
hello,明ming张
kali linux 安装一切顺利
1、但是没有列表中没有插件
<img width="684" alt="image" src="https://user-images.githubusercontent.com/18223385/48200193-55930500-e399-11e8-8794-2901230d1a4f.png">

2、配置文件中
```
 AWVS_URL = 'https://192.168.56.2:3443'  # Acunetix Web Vulnerability Scanner Url
    AWVS_API_KEY = "1986ad8c0a5b3df4d7028d5f3c06e936cb88c477b0a844e5d8582a112fc817e35"  # Acunetix Web Vulnerability Scanner API Key
```
是什么鬼哦？
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/18223385/48200487-42cd0000-e39a-11e8-995b-4145b97b1fef.png">

**Comment by jeffzh3ng** [comment]
插件需要自己上传上去，test目录下面有几个参考测试用的
这几项配置文件，在每行的后面的注释中有介绍，awvs 相关的三 awvs 扫描器 API 接口配置，UPDARTE_URL 是检查更新的，但这个是预留配置，实际没有使用
