### ISSUE TITLE
./run.sh stop,bug?

### ISSUE THREAD

**Issue by hktalent** [jeffzh3ng/Fuxi-Scanner#8]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/18223385/48200580-89baf580-e39a-11e8-951e-f56dc4c7c671.png">
```
 43912 43878  0 06:50 pts/7    00:00:00 /bin/bash ./migration/docker_start.sh

```

**Comment by jeffzh3ng** [comment]
docker_start.sh 脚本执行完 应该是会退出的
