### ISSUE TITLE
配置好了无法打开啊

### ISSUE THREAD

**Issue by sushang123** [jeffzh3ng/Fuxi-Scanner#9]
[root@localhost ~]# 
[root@localhost ~]# docker run -dit -p 5000:5000 -v /opt/data:/data -v /etc/localtime:/etc/localtime jeffzh3ng/fuxi-scanner
9e41946eb22a5d67890d696566526954fd4d7ed63930e87b352fa944216b9762
/usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint thirsty_saha (c5ab15c536d6eeb8e9aa3a408dd7465dc5841a90cfd4eb6e81cac33ca668be0d): Bind for 0.0.0.0:5000 failed: port is already allocated.

这是什么情况？

**Comment by jeffzh3ng** [comment]
根据报错来看，宿主机端口应该是被占用了，切换其他的端口试试看 -p 5001:5000
然后访问 127.0.0.1:5001 试试
